---
- name: Copy netdata.conf
  template:
    src: netdata.conf.j2
    dest: /etc/netdata/netdata.conf
    owner: netdata
    group: netdata
    mode: 0600
  notify:
    - Restart Netdata
  become: true

- name: Copy stream.conf
  template:
    src: stream.conf.j2
    dest: /etc/netdata/stream.conf
    owner: netdata
    group: netdata
    mode: 0600
  notify:
    - Restart Netdata
  become: true
