---
- name: Verify
  hosts: all
  tasks:
    - name: Check Netdata service is running
      service:
        name: netdata
        state: running
      check_mode: true
      register: presence
      failed_when: presence.changed
